---
title: "MSstatsResponse - Protein Turnover Vignette "
output: html_document
date: "2026-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load pacakges --- 
```{r}
library(MSstatsResponse)
library(tidyverse)

```

Load most recent data --- 
```{r}
quant_data_fraction_impute = readRDS("../../../ProteinTurnover/data/quant_data_fraction_imputed_new.rds")

```

manual reformatting (for now)
```{r}
# rename columns --
df_test = quant_data_fraction_impute$FeatureLevelData %>%
  mutate(
    protein_raw   = PROTEIN,
    PROTEIN       = sub("_leu6$", "", PROTEIN),
   # timepoint     = as.numeric(str_extract(GROUP, "\\d+")),
    Channel      = str_detect(protein_raw, "_leu6$")
  ) %>%
  filter(
    is.finite(INTENSITY),
    !is.na(GROUP)
  )

df_test$LABEL = ifelse(df_test$Channel == TRUE, "H", "L")


tracer_constants <- c(
  `0` = 1, `1` = 0.286, `4` = 0.294, `12` = 0.261,
  `24` = 0.304, `48` = 0.266, `96` = 0.263, `168` = 0.313
)

```

NEW FUNCTION --- 'calculateTurnoverRatios'
```{r}
test_ratio_calc = calculateTurnoverRatios(
    df_test,
    channel_col = "LABEL", #IsotopeLabel
    heavy_label = "H",
    light_label = "L",
    time_col = "GROUP",
    peptide_col = "PEPTIDE",
    protein_col = "PROTEIN",
    intensity_col = "INTENSITY",
    run_col = "RUN",
    peptide_selector = NULL,
    normalize_tracer = TRUE,
    tracer_constants = tracer_constants)

```

must rename columns --- 
```{r}
#test_ratio_calc$drug = "Synthesis"

#test_ratio_calc = MSstatsPrepareDoseResponseFit(
 # data = test_ratio_calc,
 # protein_column = 'Protein',
 # log_abundance_column = 'H_frac',
 # dose_column = 'TimeVal',
 # drug_column = 'drug')

# these column names are needed for all MSstatsResponse functions
test_ratio_calc$protein = test_ratio_calc$Protein
test_ratio_calc$drug = "Synthesis"
test_ratio_calc$dose = test_ratio_calc$TimeVal
test_ratio_calc$response = test_ratio_calc$H_frac


# add color_by option for visualization 
test_ratio_calc %>% filter (protein == example_proteins[1]) # should have 71 rows 

```


```{r}
# visualize response
visualizeResponseProtein(
  test_ratio_calc,
  protein_name = example_proteins[1],
  drug_name = "Synthesis",
  precalculated_ratios = TRUE,
  ratio_response = FALSE,
  transform_dose = FALSE,
  increasing = TRUE,
  show_ic50 = TRUE,
  add_ci = FALSE,
  target_response = 0.5, 
  y_lab = "relative abundance",x_lab = "time (hrs)",
  color_by = 'BaseSequence')


```

